/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GuildsRouteImport } from './routes/guilds'
import { Route as AdminGlobalBansRouteImport } from './routes/admin.global-bans'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardActivityHeatmapRouteImport } from './routes/dashboard/activity-heatmap'
import { Route as DashboardAiAutomodRouteImport } from './routes/dashboard/ai-automod'
import { Route as DashboardAiChatRouteImport } from './routes/dashboard/ai-chat'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard/applications'
import { Route as DashboardAutoReportsRouteImport } from './routes/dashboard/auto-reports'
import { Route as DashboardAutoRespondersRouteImport } from './routes/dashboard/auto-responders'
import { Route as DashboardAutomodRouteImport } from './routes/dashboard/automod'
import { Route as DashboardBackupsRouteImport } from './routes/dashboard/backups'
import { Route as DashboardBirthdaysRouteImport } from './routes/dashboard/birthdays'
import { Route as DashboardBotHealthRouteImport } from './routes/dashboard/bot-health'
import { Route as DashboardBotSettingsRouteImport } from './routes/dashboard/bot-settings'
import { Route as DashboardChangelogRouteImport } from './routes/dashboard/changelog'
import { Route as DashboardCharactersRouteImport } from './routes/dashboard/characters'
import { Route as DashboardCommandsRouteImport } from './routes/dashboard/commands'
import { Route as DashboardConfessionsRouteImport } from './routes/dashboard/confessions'
import { Route as DashboardCountingRouteImport } from './routes/dashboard/counting'
import { Route as DashboardCurrencyShopRouteImport } from './routes/dashboard/currency-shop'
import { Route as DashboardCustomCommandsRouteImport } from './routes/dashboard/custom-commands'
import { Route as DashboardEconomyRouteImport } from './routes/dashboard/economy'
import { Route as DashboardEmbedBuilderRouteImport } from './routes/dashboard/embed-builder'
import { Route as DashboardFeaturesRouteImport } from './routes/dashboard/features'
import { Route as DashboardFivemRouteImport } from './routes/dashboard/fivem'
import { Route as DashboardGiveawaysRouteImport } from './routes/dashboard/giveaways'
import { Route as DashboardGlobalBansRouteImport } from './routes/dashboard/global-bans'
import { Route as DashboardInviteTrackerRouteImport } from './routes/dashboard/invite-tracker'
import { Route as DashboardJtcRouteImport } from './routes/dashboard/jtc'
import { Route as DashboardLeaderboardRouteImport } from './routes/dashboard/leaderboard'
import { Route as DashboardLevelingRouteImport } from './routes/dashboard/leveling'
import { Route as DashboardLiveEventsRouteImport } from './routes/dashboard/live-events'
import { Route as DashboardLogSettingsRouteImport } from './routes/dashboard/log-settings'
import { Route as DashboardLogsRouteImport } from './routes/dashboard/logs'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardModerationRouteImport } from './routes/dashboard/moderation'
import { Route as DashboardModmailRouteImport } from './routes/dashboard/modmail'
import { Route as DashboardModulesRouteImport } from './routes/dashboard/modules'
import { Route as DashboardMusicQuizRouteImport } from './routes/dashboard/music-quiz'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardPollsRouteImport } from './routes/dashboard/polls'
import { Route as DashboardQuarantineRouteImport } from './routes/dashboard/quarantine'
import { Route as DashboardRaidProtectionRouteImport } from './routes/dashboard/raid-protection'
import { Route as DashboardReactionRolesRouteImport } from './routes/dashboard/reaction-roles'
import { Route as DashboardRemindersRouteImport } from './routes/dashboard/reminders'
import { Route as DashboardRoleAnalyticsRouteImport } from './routes/dashboard/role-analytics'
import { Route as DashboardScheduledActionsRouteImport } from './routes/dashboard/scheduled-actions'
import { Route as DashboardSchedulerRouteImport } from './routes/dashboard/scheduler'
import { Route as DashboardServerCloneRouteImport } from './routes/dashboard/server-clone'
import { Route as DashboardSlowmodeSchedulerRouteImport } from './routes/dashboard/slowmode-scheduler'
import { Route as DashboardStarboardRouteImport } from './routes/dashboard/starboard'
import { Route as DashboardStatsChannelsRouteImport } from './routes/dashboard/stats-channels'
import { Route as DashboardSuggestionsRouteImport } from './routes/dashboard/suggestions'
import { Route as DashboardTebexRouteImport } from './routes/dashboard/tebex'
import { Route as DashboardTestPanelRouteImport } from './routes/dashboard/test-panel'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard/tickets'
import { Route as DashboardTiktokRouteImport } from './routes/dashboard/tiktok'
import { Route as DashboardTwitchRouteImport } from './routes/dashboard/twitch'
import { Route as DashboardVerificationRouteImport } from './routes/dashboard/verification'
import { Route as DashboardWarningsRouteImport } from './routes/dashboard/warnings'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard/webhooks'
import { Route as DashboardWelcomeRouteImport } from './routes/dashboard/welcome'
import { Route as DashboardYoutubeRouteImport } from './routes/dashboard/youtube'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsLayoutRouteImport } from './routes/docs/_layout'
import { Route as DashboardApplicationsSubmissionIdRouteImport } from './routes/dashboard/applications.$submissionId'
import { Route as DashboardApplicationsAnalyticsRouteImport } from './routes/dashboard/applications.analytics'
import { Route as DashboardApplicationsSettingsRouteImport } from './routes/dashboard/applications.settings'
import { Route as DashboardTicketsTicketIdRouteImport } from './routes/dashboard/tickets.$ticketId'
import { Route as DashboardTicketsSettingsRouteImport } from './routes/dashboard/tickets.settings'
import { Route as DocsCategorySlugRouteImport } from './routes/docs/$category.$slug'
import { Route as DashboardApplicationsFormsFormIdRouteImport } from './routes/dashboard/applications.forms.$formId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsRoute = GuildsRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGlobalBansRoute = AdminGlobalBansRouteImport.update({
  id: '/global-bans',
  path: '/global-bans',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardActivityHeatmapRoute =
  DashboardActivityHeatmapRouteImport.update({
    id: '/dashboard/activity-heatmap',
    path: '/dashboard/activity-heatmap',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAiAutomodRoute = DashboardAiAutomodRouteImport.update({
  id: '/dashboard/ai-automod',
  path: '/dashboard/ai-automod',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiChatRoute = DashboardAiChatRouteImport.update({
  id: '/dashboard/ai-chat',
  path: '/dashboard/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/dashboard/applications',
  path: '/dashboard/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAutoReportsRoute = DashboardAutoReportsRouteImport.update({
  id: '/dashboard/auto-reports',
  path: '/dashboard/auto-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAutoRespondersRoute = DashboardAutoRespondersRouteImport.update({
  id: '/dashboard/auto-responders',
  path: '/dashboard/auto-responders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAutomodRoute = DashboardAutomodRouteImport.update({
  id: '/dashboard/automod',
  path: '/dashboard/automod',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBackupsRoute = DashboardBackupsRouteImport.update({
  id: '/dashboard/backups',
  path: '/dashboard/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBirthdaysRoute = DashboardBirthdaysRouteImport.update({
  id: '/dashboard/birthdays',
  path: '/dashboard/birthdays',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBotHealthRoute = DashboardBotHealthRouteImport.update({
  id: '/dashboard/bot-health',
  path: '/dashboard/bot-health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBotSettingsRoute = DashboardBotSettingsRouteImport.update({
  id: '/dashboard/bot-settings',
  path: '/dashboard/bot-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChangelogRoute = DashboardChangelogRouteImport.update({
  id: '/dashboard/changelog',
  path: '/dashboard/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCharactersRoute = DashboardCharactersRouteImport.update({
  id: '/dashboard/characters',
  path: '/dashboard/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCommandsRoute = DashboardCommandsRouteImport.update({
  id: '/dashboard/commands',
  path: '/dashboard/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConfessionsRoute = DashboardConfessionsRouteImport.update({
  id: '/dashboard/confessions',
  path: '/dashboard/confessions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCountingRoute = DashboardCountingRouteImport.update({
  id: '/dashboard/counting',
  path: '/dashboard/counting',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCurrencyShopRoute = DashboardCurrencyShopRouteImport.update({
  id: '/dashboard/currency-shop',
  path: '/dashboard/currency-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomCommandsRoute = DashboardCustomCommandsRouteImport.update({
  id: '/dashboard/custom-commands',
  path: '/dashboard/custom-commands',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEconomyRoute = DashboardEconomyRouteImport.update({
  id: '/dashboard/economy',
  path: '/dashboard/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmbedBuilderRoute = DashboardEmbedBuilderRouteImport.update({
  id: '/dashboard/embed-builder',
  path: '/dashboard/embed-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFeaturesRoute = DashboardFeaturesRouteImport.update({
  id: '/dashboard/features',
  path: '/dashboard/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFivemRoute = DashboardFivemRouteImport.update({
  id: '/dashboard/fivem',
  path: '/dashboard/fivem',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGiveawaysRoute = DashboardGiveawaysRouteImport.update({
  id: '/dashboard/giveaways',
  path: '/dashboard/giveaways',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGlobalBansRoute = DashboardGlobalBansRouteImport.update({
  id: '/dashboard/global-bans',
  path: '/dashboard/global-bans',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInviteTrackerRoute = DashboardInviteTrackerRouteImport.update({
  id: '/dashboard/invite-tracker',
  path: '/dashboard/invite-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardJtcRoute = DashboardJtcRouteImport.update({
  id: '/dashboard/jtc',
  path: '/dashboard/jtc',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeaderboardRoute = DashboardLeaderboardRouteImport.update({
  id: '/dashboard/leaderboard',
  path: '/dashboard/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLevelingRoute = DashboardLevelingRouteImport.update({
  id: '/dashboard/leveling',
  path: '/dashboard/leveling',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLiveEventsRoute = DashboardLiveEventsRouteImport.update({
  id: '/dashboard/live-events',
  path: '/dashboard/live-events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLogSettingsRoute = DashboardLogSettingsRouteImport.update({
  id: '/dashboard/log-settings',
  path: '/dashboard/log-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/dashboard/logs',
  path: '/dashboard/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/dashboard/members',
  path: '/dashboard/members',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardModerationRoute = DashboardModerationRouteImport.update({
  id: '/dashboard/moderation',
  path: '/dashboard/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardModmailRoute = DashboardModmailRouteImport.update({
  id: '/dashboard/modmail',
  path: '/dashboard/modmail',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardModulesRoute = DashboardModulesRouteImport.update({
  id: '/dashboard/modules',
  path: '/dashboard/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMusicQuizRoute = DashboardMusicQuizRouteImport.update({
  id: '/dashboard/music-quiz',
  path: '/dashboard/music-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPollsRoute = DashboardPollsRouteImport.update({
  id: '/dashboard/polls',
  path: '/dashboard/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQuarantineRoute = DashboardQuarantineRouteImport.update({
  id: '/dashboard/quarantine',
  path: '/dashboard/quarantine',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRaidProtectionRoute = DashboardRaidProtectionRouteImport.update({
  id: '/dashboard/raid-protection',
  path: '/dashboard/raid-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReactionRolesRoute = DashboardReactionRolesRouteImport.update({
  id: '/dashboard/reaction-roles',
  path: '/dashboard/reaction-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRemindersRoute = DashboardRemindersRouteImport.update({
  id: '/dashboard/reminders',
  path: '/dashboard/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleAnalyticsRoute = DashboardRoleAnalyticsRouteImport.update({
  id: '/dashboard/role-analytics',
  path: '/dashboard/role-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScheduledActionsRoute =
  DashboardScheduledActionsRouteImport.update({
    id: '/dashboard/scheduled-actions',
    path: '/dashboard/scheduled-actions',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSchedulerRoute = DashboardSchedulerRouteImport.update({
  id: '/dashboard/scheduler',
  path: '/dashboard/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServerCloneRoute = DashboardServerCloneRouteImport.update({
  id: '/dashboard/server-clone',
  path: '/dashboard/server-clone',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSlowmodeSchedulerRoute =
  DashboardSlowmodeSchedulerRouteImport.update({
    id: '/dashboard/slowmode-scheduler',
    path: '/dashboard/slowmode-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardStarboardRoute = DashboardStarboardRouteImport.update({
  id: '/dashboard/starboard',
  path: '/dashboard/starboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStatsChannelsRoute = DashboardStatsChannelsRouteImport.update({
  id: '/dashboard/stats-channels',
  path: '/dashboard/stats-channels',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSuggestionsRoute = DashboardSuggestionsRouteImport.update({
  id: '/dashboard/suggestions',
  path: '/dashboard/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTebexRoute = DashboardTebexRouteImport.update({
  id: '/dashboard/tebex',
  path: '/dashboard/tebex',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestPanelRoute = DashboardTestPanelRouteImport.update({
  id: '/dashboard/test-panel',
  path: '/dashboard/test-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/dashboard/tickets',
  path: '/dashboard/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTiktokRoute = DashboardTiktokRouteImport.update({
  id: '/dashboard/tiktok',
  path: '/dashboard/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTwitchRoute = DashboardTwitchRouteImport.update({
  id: '/dashboard/twitch',
  path: '/dashboard/twitch',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVerificationRoute = DashboardVerificationRouteImport.update({
  id: '/dashboard/verification',
  path: '/dashboard/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWarningsRoute = DashboardWarningsRouteImport.update({
  id: '/dashboard/warnings',
  path: '/dashboard/warnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/dashboard/webhooks',
  path: '/dashboard/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWelcomeRoute = DashboardWelcomeRouteImport.update({
  id: '/dashboard/welcome',
  path: '/dashboard/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardYoutubeRoute = DashboardYoutubeRouteImport.update({
  id: '/dashboard/youtube',
  path: '/dashboard/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLayoutRoute = DocsLayoutRouteImport.update({
  id: '/docs/_layout',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApplicationsSubmissionIdRoute =
  DashboardApplicationsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => DashboardApplicationsRoute,
  } as any)
const DashboardApplicationsAnalyticsRoute =
  DashboardApplicationsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardApplicationsRoute,
  } as any)
const DashboardApplicationsSettingsRoute =
  DashboardApplicationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardApplicationsRoute,
  } as any)
const DashboardTicketsTicketIdRoute =
  DashboardTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => DashboardTicketsRoute,
  } as any)
const DashboardTicketsSettingsRoute =
  DashboardTicketsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardTicketsRoute,
  } as any)
const DocsCategorySlugRoute = DocsCategorySlugRouteImport.update({
  id: '/docs/$category/$slug',
  path: '/docs/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApplicationsFormsFormIdRoute =
  DashboardApplicationsFormsFormIdRouteImport.update({
    id: '/forms/$formId',
    path: '/forms/$formId',
    getParentRoute: () => DashboardApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/guilds': typeof GuildsRoute
  '/admin/global-bans': typeof AdminGlobalBansRoute
  '/dashboard': typeof DashboardLayoutRoute
  '/dashboard/activity-heatmap': typeof DashboardActivityHeatmapRoute
  '/dashboard/ai-automod': typeof DashboardAiAutomodRoute
  '/dashboard/ai-chat': typeof DashboardAiChatRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRouteWithChildren
  '/dashboard/auto-reports': typeof DashboardAutoReportsRoute
  '/dashboard/auto-responders': typeof DashboardAutoRespondersRoute
  '/dashboard/automod': typeof DashboardAutomodRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/birthdays': typeof DashboardBirthdaysRoute
  '/dashboard/bot-health': typeof DashboardBotHealthRoute
  '/dashboard/bot-settings': typeof DashboardBotSettingsRoute
  '/dashboard/changelog': typeof DashboardChangelogRoute
  '/dashboard/characters': typeof DashboardCharactersRoute
  '/dashboard/commands': typeof DashboardCommandsRoute
  '/dashboard/confessions': typeof DashboardConfessionsRoute
  '/dashboard/counting': typeof DashboardCountingRoute
  '/dashboard/currency-shop': typeof DashboardCurrencyShopRoute
  '/dashboard/custom-commands': typeof DashboardCustomCommandsRoute
  '/dashboard/economy': typeof DashboardEconomyRoute
  '/dashboard/embed-builder': typeof DashboardEmbedBuilderRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/fivem': typeof DashboardFivemRoute
  '/dashboard/giveaways': typeof DashboardGiveawaysRoute
  '/dashboard/global-bans': typeof DashboardGlobalBansRoute
  '/dashboard/invite-tracker': typeof DashboardInviteTrackerRoute
  '/dashboard/jtc': typeof DashboardJtcRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/leveling': typeof DashboardLevelingRoute
  '/dashboard/live-events': typeof DashboardLiveEventsRoute
  '/dashboard/log-settings': typeof DashboardLogSettingsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/moderation': typeof DashboardModerationRoute
  '/dashboard/modmail': typeof DashboardModmailRoute
  '/dashboard/modules': typeof DashboardModulesRoute
  '/dashboard/music-quiz': typeof DashboardMusicQuizRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/polls': typeof DashboardPollsRoute
  '/dashboard/quarantine': typeof DashboardQuarantineRoute
  '/dashboard/raid-protection': typeof DashboardRaidProtectionRoute
  '/dashboard/reaction-roles': typeof DashboardReactionRolesRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/role-analytics': typeof DashboardRoleAnalyticsRoute
  '/dashboard/scheduled-actions': typeof DashboardScheduledActionsRoute
  '/dashboard/scheduler': typeof DashboardSchedulerRoute
  '/dashboard/server-clone': typeof DashboardServerCloneRoute
  '/dashboard/slowmode-scheduler': typeof DashboardSlowmodeSchedulerRoute
  '/dashboard/starboard': typeof DashboardStarboardRoute
  '/dashboard/stats-channels': typeof DashboardStatsChannelsRoute
  '/dashboard/suggestions': typeof DashboardSuggestionsRoute
  '/dashboard/tebex': typeof DashboardTebexRoute
  '/dashboard/test-panel': typeof DashboardTestPanelRoute
  '/dashboard/tickets': typeof DashboardTicketsRouteWithChildren
  '/dashboard/tiktok': typeof DashboardTiktokRoute
  '/dashboard/twitch': typeof DashboardTwitchRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/dashboard/warnings': typeof DashboardWarningsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/welcome': typeof DashboardWelcomeRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
  '/docs': typeof DocsLayoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/applications/$submissionId': typeof DashboardApplicationsSubmissionIdRoute
  '/dashboard/applications/analytics': typeof DashboardApplicationsAnalyticsRoute
  '/dashboard/applications/settings': typeof DashboardApplicationsSettingsRoute
  '/dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/dashboard/tickets/settings': typeof DashboardTicketsSettingsRoute
  '/docs/$category/$slug': typeof DocsCategorySlugRoute
  '/dashboard/applications/forms/$formId': typeof DashboardApplicationsFormsFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/guilds': typeof GuildsRoute
  '/admin/global-bans': typeof AdminGlobalBansRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/activity-heatmap': typeof DashboardActivityHeatmapRoute
  '/dashboard/ai-automod': typeof DashboardAiAutomodRoute
  '/dashboard/ai-chat': typeof DashboardAiChatRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRouteWithChildren
  '/dashboard/auto-reports': typeof DashboardAutoReportsRoute
  '/dashboard/auto-responders': typeof DashboardAutoRespondersRoute
  '/dashboard/automod': typeof DashboardAutomodRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/birthdays': typeof DashboardBirthdaysRoute
  '/dashboard/bot-health': typeof DashboardBotHealthRoute
  '/dashboard/bot-settings': typeof DashboardBotSettingsRoute
  '/dashboard/changelog': typeof DashboardChangelogRoute
  '/dashboard/characters': typeof DashboardCharactersRoute
  '/dashboard/commands': typeof DashboardCommandsRoute
  '/dashboard/confessions': typeof DashboardConfessionsRoute
  '/dashboard/counting': typeof DashboardCountingRoute
  '/dashboard/currency-shop': typeof DashboardCurrencyShopRoute
  '/dashboard/custom-commands': typeof DashboardCustomCommandsRoute
  '/dashboard/economy': typeof DashboardEconomyRoute
  '/dashboard/embed-builder': typeof DashboardEmbedBuilderRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/fivem': typeof DashboardFivemRoute
  '/dashboard/giveaways': typeof DashboardGiveawaysRoute
  '/dashboard/global-bans': typeof DashboardGlobalBansRoute
  '/dashboard/invite-tracker': typeof DashboardInviteTrackerRoute
  '/dashboard/jtc': typeof DashboardJtcRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/leveling': typeof DashboardLevelingRoute
  '/dashboard/live-events': typeof DashboardLiveEventsRoute
  '/dashboard/log-settings': typeof DashboardLogSettingsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/moderation': typeof DashboardModerationRoute
  '/dashboard/modmail': typeof DashboardModmailRoute
  '/dashboard/modules': typeof DashboardModulesRoute
  '/dashboard/music-quiz': typeof DashboardMusicQuizRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/polls': typeof DashboardPollsRoute
  '/dashboard/quarantine': typeof DashboardQuarantineRoute
  '/dashboard/raid-protection': typeof DashboardRaidProtectionRoute
  '/dashboard/reaction-roles': typeof DashboardReactionRolesRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/role-analytics': typeof DashboardRoleAnalyticsRoute
  '/dashboard/scheduled-actions': typeof DashboardScheduledActionsRoute
  '/dashboard/scheduler': typeof DashboardSchedulerRoute
  '/dashboard/server-clone': typeof DashboardServerCloneRoute
  '/dashboard/slowmode-scheduler': typeof DashboardSlowmodeSchedulerRoute
  '/dashboard/starboard': typeof DashboardStarboardRoute
  '/dashboard/stats-channels': typeof DashboardStatsChannelsRoute
  '/dashboard/suggestions': typeof DashboardSuggestionsRoute
  '/dashboard/tebex': typeof DashboardTebexRoute
  '/dashboard/test-panel': typeof DashboardTestPanelRoute
  '/dashboard/tickets': typeof DashboardTicketsRouteWithChildren
  '/dashboard/tiktok': typeof DashboardTiktokRoute
  '/dashboard/twitch': typeof DashboardTwitchRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/dashboard/warnings': typeof DashboardWarningsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/welcome': typeof DashboardWelcomeRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard/applications/$submissionId': typeof DashboardApplicationsSubmissionIdRoute
  '/dashboard/applications/analytics': typeof DashboardApplicationsAnalyticsRoute
  '/dashboard/applications/settings': typeof DashboardApplicationsSettingsRoute
  '/dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/dashboard/tickets/settings': typeof DashboardTicketsSettingsRoute
  '/docs/$category/$slug': typeof DocsCategorySlugRoute
  '/dashboard/applications/forms/$formId': typeof DashboardApplicationsFormsFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/guilds': typeof GuildsRoute
  '/admin/global-bans': typeof AdminGlobalBansRoute
  '/dashboard/_layout': typeof DashboardLayoutRoute
  '/dashboard/activity-heatmap': typeof DashboardActivityHeatmapRoute
  '/dashboard/ai-automod': typeof DashboardAiAutomodRoute
  '/dashboard/ai-chat': typeof DashboardAiChatRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRouteWithChildren
  '/dashboard/auto-reports': typeof DashboardAutoReportsRoute
  '/dashboard/auto-responders': typeof DashboardAutoRespondersRoute
  '/dashboard/automod': typeof DashboardAutomodRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/birthdays': typeof DashboardBirthdaysRoute
  '/dashboard/bot-health': typeof DashboardBotHealthRoute
  '/dashboard/bot-settings': typeof DashboardBotSettingsRoute
  '/dashboard/changelog': typeof DashboardChangelogRoute
  '/dashboard/characters': typeof DashboardCharactersRoute
  '/dashboard/commands': typeof DashboardCommandsRoute
  '/dashboard/confessions': typeof DashboardConfessionsRoute
  '/dashboard/counting': typeof DashboardCountingRoute
  '/dashboard/currency-shop': typeof DashboardCurrencyShopRoute
  '/dashboard/custom-commands': typeof DashboardCustomCommandsRoute
  '/dashboard/economy': typeof DashboardEconomyRoute
  '/dashboard/embed-builder': typeof DashboardEmbedBuilderRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/fivem': typeof DashboardFivemRoute
  '/dashboard/giveaways': typeof DashboardGiveawaysRoute
  '/dashboard/global-bans': typeof DashboardGlobalBansRoute
  '/dashboard/invite-tracker': typeof DashboardInviteTrackerRoute
  '/dashboard/jtc': typeof DashboardJtcRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/leveling': typeof DashboardLevelingRoute
  '/dashboard/live-events': typeof DashboardLiveEventsRoute
  '/dashboard/log-settings': typeof DashboardLogSettingsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/moderation': typeof DashboardModerationRoute
  '/dashboard/modmail': typeof DashboardModmailRoute
  '/dashboard/modules': typeof DashboardModulesRoute
  '/dashboard/music-quiz': typeof DashboardMusicQuizRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/polls': typeof DashboardPollsRoute
  '/dashboard/quarantine': typeof DashboardQuarantineRoute
  '/dashboard/raid-protection': typeof DashboardRaidProtectionRoute
  '/dashboard/reaction-roles': typeof DashboardReactionRolesRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/role-analytics': typeof DashboardRoleAnalyticsRoute
  '/dashboard/scheduled-actions': typeof DashboardScheduledActionsRoute
  '/dashboard/scheduler': typeof DashboardSchedulerRoute
  '/dashboard/server-clone': typeof DashboardServerCloneRoute
  '/dashboard/slowmode-scheduler': typeof DashboardSlowmodeSchedulerRoute
  '/dashboard/starboard': typeof DashboardStarboardRoute
  '/dashboard/stats-channels': typeof DashboardStatsChannelsRoute
  '/dashboard/suggestions': typeof DashboardSuggestionsRoute
  '/dashboard/tebex': typeof DashboardTebexRoute
  '/dashboard/test-panel': typeof DashboardTestPanelRoute
  '/dashboard/tickets': typeof DashboardTicketsRouteWithChildren
  '/dashboard/tiktok': typeof DashboardTiktokRoute
  '/dashboard/twitch': typeof DashboardTwitchRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/dashboard/warnings': typeof DashboardWarningsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/welcome': typeof DashboardWelcomeRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
  '/docs/_layout': typeof DocsLayoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/applications/$submissionId': typeof DashboardApplicationsSubmissionIdRoute
  '/dashboard/applications/analytics': typeof DashboardApplicationsAnalyticsRoute
  '/dashboard/applications/settings': typeof DashboardApplicationsSettingsRoute
  '/dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/dashboard/tickets/settings': typeof DashboardTicketsSettingsRoute
  '/docs/$category/$slug': typeof DocsCategorySlugRoute
  '/dashboard/applications/forms/$formId': typeof DashboardApplicationsFormsFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/guilds'
    | '/admin/global-bans'
    | '/dashboard'
    | '/dashboard/activity-heatmap'
    | '/dashboard/ai-automod'
    | '/dashboard/ai-chat'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/auto-reports'
    | '/dashboard/auto-responders'
    | '/dashboard/automod'
    | '/dashboard/backups'
    | '/dashboard/birthdays'
    | '/dashboard/bot-health'
    | '/dashboard/bot-settings'
    | '/dashboard/changelog'
    | '/dashboard/characters'
    | '/dashboard/commands'
    | '/dashboard/confessions'
    | '/dashboard/counting'
    | '/dashboard/currency-shop'
    | '/dashboard/custom-commands'
    | '/dashboard/economy'
    | '/dashboard/embed-builder'
    | '/dashboard/features'
    | '/dashboard/fivem'
    | '/dashboard/giveaways'
    | '/dashboard/global-bans'
    | '/dashboard/invite-tracker'
    | '/dashboard/jtc'
    | '/dashboard/leaderboard'
    | '/dashboard/leveling'
    | '/dashboard/live-events'
    | '/dashboard/log-settings'
    | '/dashboard/logs'
    | '/dashboard/members'
    | '/dashboard/moderation'
    | '/dashboard/modmail'
    | '/dashboard/modules'
    | '/dashboard/music-quiz'
    | '/dashboard/notifications'
    | '/dashboard/polls'
    | '/dashboard/quarantine'
    | '/dashboard/raid-protection'
    | '/dashboard/reaction-roles'
    | '/dashboard/reminders'
    | '/dashboard/role-analytics'
    | '/dashboard/scheduled-actions'
    | '/dashboard/scheduler'
    | '/dashboard/server-clone'
    | '/dashboard/slowmode-scheduler'
    | '/dashboard/starboard'
    | '/dashboard/stats-channels'
    | '/dashboard/suggestions'
    | '/dashboard/tebex'
    | '/dashboard/test-panel'
    | '/dashboard/tickets'
    | '/dashboard/tiktok'
    | '/dashboard/twitch'
    | '/dashboard/verification'
    | '/dashboard/warnings'
    | '/dashboard/webhooks'
    | '/dashboard/welcome'
    | '/dashboard/youtube'
    | '/docs'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/applications/$submissionId'
    | '/dashboard/applications/analytics'
    | '/dashboard/applications/settings'
    | '/dashboard/tickets/$ticketId'
    | '/dashboard/tickets/settings'
    | '/docs/$category/$slug'
    | '/dashboard/applications/forms/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/guilds'
    | '/admin/global-bans'
    | '/dashboard'
    | '/dashboard/activity-heatmap'
    | '/dashboard/ai-automod'
    | '/dashboard/ai-chat'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/auto-reports'
    | '/dashboard/auto-responders'
    | '/dashboard/automod'
    | '/dashboard/backups'
    | '/dashboard/birthdays'
    | '/dashboard/bot-health'
    | '/dashboard/bot-settings'
    | '/dashboard/changelog'
    | '/dashboard/characters'
    | '/dashboard/commands'
    | '/dashboard/confessions'
    | '/dashboard/counting'
    | '/dashboard/currency-shop'
    | '/dashboard/custom-commands'
    | '/dashboard/economy'
    | '/dashboard/embed-builder'
    | '/dashboard/features'
    | '/dashboard/fivem'
    | '/dashboard/giveaways'
    | '/dashboard/global-bans'
    | '/dashboard/invite-tracker'
    | '/dashboard/jtc'
    | '/dashboard/leaderboard'
    | '/dashboard/leveling'
    | '/dashboard/live-events'
    | '/dashboard/log-settings'
    | '/dashboard/logs'
    | '/dashboard/members'
    | '/dashboard/moderation'
    | '/dashboard/modmail'
    | '/dashboard/modules'
    | '/dashboard/music-quiz'
    | '/dashboard/notifications'
    | '/dashboard/polls'
    | '/dashboard/quarantine'
    | '/dashboard/raid-protection'
    | '/dashboard/reaction-roles'
    | '/dashboard/reminders'
    | '/dashboard/role-analytics'
    | '/dashboard/scheduled-actions'
    | '/dashboard/scheduler'
    | '/dashboard/server-clone'
    | '/dashboard/slowmode-scheduler'
    | '/dashboard/starboard'
    | '/dashboard/stats-channels'
    | '/dashboard/suggestions'
    | '/dashboard/tebex'
    | '/dashboard/test-panel'
    | '/dashboard/tickets'
    | '/dashboard/tiktok'
    | '/dashboard/twitch'
    | '/dashboard/verification'
    | '/dashboard/warnings'
    | '/dashboard/webhooks'
    | '/dashboard/welcome'
    | '/dashboard/youtube'
    | '/docs'
    | '/dashboard/applications/$submissionId'
    | '/dashboard/applications/analytics'
    | '/dashboard/applications/settings'
    | '/dashboard/tickets/$ticketId'
    | '/dashboard/tickets/settings'
    | '/docs/$category/$slug'
    | '/dashboard/applications/forms/$formId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/guilds'
    | '/admin/global-bans'
    | '/dashboard/_layout'
    | '/dashboard/activity-heatmap'
    | '/dashboard/ai-automod'
    | '/dashboard/ai-chat'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/auto-reports'
    | '/dashboard/auto-responders'
    | '/dashboard/automod'
    | '/dashboard/backups'
    | '/dashboard/birthdays'
    | '/dashboard/bot-health'
    | '/dashboard/bot-settings'
    | '/dashboard/changelog'
    | '/dashboard/characters'
    | '/dashboard/commands'
    | '/dashboard/confessions'
    | '/dashboard/counting'
    | '/dashboard/currency-shop'
    | '/dashboard/custom-commands'
    | '/dashboard/economy'
    | '/dashboard/embed-builder'
    | '/dashboard/features'
    | '/dashboard/fivem'
    | '/dashboard/giveaways'
    | '/dashboard/global-bans'
    | '/dashboard/invite-tracker'
    | '/dashboard/jtc'
    | '/dashboard/leaderboard'
    | '/dashboard/leveling'
    | '/dashboard/live-events'
    | '/dashboard/log-settings'
    | '/dashboard/logs'
    | '/dashboard/members'
    | '/dashboard/moderation'
    | '/dashboard/modmail'
    | '/dashboard/modules'
    | '/dashboard/music-quiz'
    | '/dashboard/notifications'
    | '/dashboard/polls'
    | '/dashboard/quarantine'
    | '/dashboard/raid-protection'
    | '/dashboard/reaction-roles'
    | '/dashboard/reminders'
    | '/dashboard/role-analytics'
    | '/dashboard/scheduled-actions'
    | '/dashboard/scheduler'
    | '/dashboard/server-clone'
    | '/dashboard/slowmode-scheduler'
    | '/dashboard/starboard'
    | '/dashboard/stats-channels'
    | '/dashboard/suggestions'
    | '/dashboard/tebex'
    | '/dashboard/test-panel'
    | '/dashboard/tickets'
    | '/dashboard/tiktok'
    | '/dashboard/twitch'
    | '/dashboard/verification'
    | '/dashboard/warnings'
    | '/dashboard/webhooks'
    | '/dashboard/welcome'
    | '/dashboard/youtube'
    | '/docs/_layout'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/applications/$submissionId'
    | '/dashboard/applications/analytics'
    | '/dashboard/applications/settings'
    | '/dashboard/tickets/$ticketId'
    | '/dashboard/tickets/settings'
    | '/docs/$category/$slug'
    | '/dashboard/applications/forms/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  GuildsRoute: typeof GuildsRoute
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  DashboardActivityHeatmapRoute: typeof DashboardActivityHeatmapRoute
  DashboardAiAutomodRoute: typeof DashboardAiAutomodRoute
  DashboardAiChatRoute: typeof DashboardAiChatRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRouteWithChildren
  DashboardAutoReportsRoute: typeof DashboardAutoReportsRoute
  DashboardAutoRespondersRoute: typeof DashboardAutoRespondersRoute
  DashboardAutomodRoute: typeof DashboardAutomodRoute
  DashboardBackupsRoute: typeof DashboardBackupsRoute
  DashboardBirthdaysRoute: typeof DashboardBirthdaysRoute
  DashboardBotHealthRoute: typeof DashboardBotHealthRoute
  DashboardBotSettingsRoute: typeof DashboardBotSettingsRoute
  DashboardChangelogRoute: typeof DashboardChangelogRoute
  DashboardCharactersRoute: typeof DashboardCharactersRoute
  DashboardCommandsRoute: typeof DashboardCommandsRoute
  DashboardConfessionsRoute: typeof DashboardConfessionsRoute
  DashboardCountingRoute: typeof DashboardCountingRoute
  DashboardCurrencyShopRoute: typeof DashboardCurrencyShopRoute
  DashboardCustomCommandsRoute: typeof DashboardCustomCommandsRoute
  DashboardEconomyRoute: typeof DashboardEconomyRoute
  DashboardEmbedBuilderRoute: typeof DashboardEmbedBuilderRoute
  DashboardFeaturesRoute: typeof DashboardFeaturesRoute
  DashboardFivemRoute: typeof DashboardFivemRoute
  DashboardGiveawaysRoute: typeof DashboardGiveawaysRoute
  DashboardGlobalBansRoute: typeof DashboardGlobalBansRoute
  DashboardInviteTrackerRoute: typeof DashboardInviteTrackerRoute
  DashboardJtcRoute: typeof DashboardJtcRoute
  DashboardLeaderboardRoute: typeof DashboardLeaderboardRoute
  DashboardLevelingRoute: typeof DashboardLevelingRoute
  DashboardLiveEventsRoute: typeof DashboardLiveEventsRoute
  DashboardLogSettingsRoute: typeof DashboardLogSettingsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardModerationRoute: typeof DashboardModerationRoute
  DashboardModmailRoute: typeof DashboardModmailRoute
  DashboardModulesRoute: typeof DashboardModulesRoute
  DashboardMusicQuizRoute: typeof DashboardMusicQuizRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPollsRoute: typeof DashboardPollsRoute
  DashboardQuarantineRoute: typeof DashboardQuarantineRoute
  DashboardRaidProtectionRoute: typeof DashboardRaidProtectionRoute
  DashboardReactionRolesRoute: typeof DashboardReactionRolesRoute
  DashboardRemindersRoute: typeof DashboardRemindersRoute
  DashboardRoleAnalyticsRoute: typeof DashboardRoleAnalyticsRoute
  DashboardScheduledActionsRoute: typeof DashboardScheduledActionsRoute
  DashboardSchedulerRoute: typeof DashboardSchedulerRoute
  DashboardServerCloneRoute: typeof DashboardServerCloneRoute
  DashboardSlowmodeSchedulerRoute: typeof DashboardSlowmodeSchedulerRoute
  DashboardStarboardRoute: typeof DashboardStarboardRoute
  DashboardStatsChannelsRoute: typeof DashboardStatsChannelsRoute
  DashboardSuggestionsRoute: typeof DashboardSuggestionsRoute
  DashboardTebexRoute: typeof DashboardTebexRoute
  DashboardTestPanelRoute: typeof DashboardTestPanelRoute
  DashboardTicketsRoute: typeof DashboardTicketsRouteWithChildren
  DashboardTiktokRoute: typeof DashboardTiktokRoute
  DashboardTwitchRoute: typeof DashboardTwitchRoute
  DashboardVerificationRoute: typeof DashboardVerificationRoute
  DashboardWarningsRoute: typeof DashboardWarningsRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardWelcomeRoute: typeof DashboardWelcomeRoute
  DashboardYoutubeRoute: typeof DashboardYoutubeRoute
  DocsLayoutRoute: typeof DocsLayoutRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsCategorySlugRoute: typeof DocsCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds': {
      id: '/guilds'
      path: '/guilds'
      fullPath: '/guilds'
      preLoaderRoute: typeof GuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/global-bans': {
      id: '/admin/global-bans'
      path: '/global-bans'
      fullPath: '/admin/global-bans'
      preLoaderRoute: typeof AdminGlobalBansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/activity-heatmap': {
      id: '/dashboard/activity-heatmap'
      path: '/dashboard/activity-heatmap'
      fullPath: '/dashboard/activity-heatmap'
      preLoaderRoute: typeof DashboardActivityHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai-automod': {
      id: '/dashboard/ai-automod'
      path: '/dashboard/ai-automod'
      fullPath: '/dashboard/ai-automod'
      preLoaderRoute: typeof DashboardAiAutomodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai-chat': {
      id: '/dashboard/ai-chat'
      path: '/dashboard/ai-chat'
      fullPath: '/dashboard/ai-chat'
      preLoaderRoute: typeof DashboardAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/dashboard/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/auto-reports': {
      id: '/dashboard/auto-reports'
      path: '/dashboard/auto-reports'
      fullPath: '/dashboard/auto-reports'
      preLoaderRoute: typeof DashboardAutoReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/auto-responders': {
      id: '/dashboard/auto-responders'
      path: '/dashboard/auto-responders'
      fullPath: '/dashboard/auto-responders'
      preLoaderRoute: typeof DashboardAutoRespondersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/automod': {
      id: '/dashboard/automod'
      path: '/dashboard/automod'
      fullPath: '/dashboard/automod'
      preLoaderRoute: typeof DashboardAutomodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/backups': {
      id: '/dashboard/backups'
      path: '/dashboard/backups'
      fullPath: '/dashboard/backups'
      preLoaderRoute: typeof DashboardBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/birthdays': {
      id: '/dashboard/birthdays'
      path: '/dashboard/birthdays'
      fullPath: '/dashboard/birthdays'
      preLoaderRoute: typeof DashboardBirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bot-health': {
      id: '/dashboard/bot-health'
      path: '/dashboard/bot-health'
      fullPath: '/dashboard/bot-health'
      preLoaderRoute: typeof DashboardBotHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bot-settings': {
      id: '/dashboard/bot-settings'
      path: '/dashboard/bot-settings'
      fullPath: '/dashboard/bot-settings'
      preLoaderRoute: typeof DashboardBotSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/changelog': {
      id: '/dashboard/changelog'
      path: '/dashboard/changelog'
      fullPath: '/dashboard/changelog'
      preLoaderRoute: typeof DashboardChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/characters': {
      id: '/dashboard/characters'
      path: '/dashboard/characters'
      fullPath: '/dashboard/characters'
      preLoaderRoute: typeof DashboardCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/commands': {
      id: '/dashboard/commands'
      path: '/dashboard/commands'
      fullPath: '/dashboard/commands'
      preLoaderRoute: typeof DashboardCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/confessions': {
      id: '/dashboard/confessions'
      path: '/dashboard/confessions'
      fullPath: '/dashboard/confessions'
      preLoaderRoute: typeof DashboardConfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/counting': {
      id: '/dashboard/counting'
      path: '/dashboard/counting'
      fullPath: '/dashboard/counting'
      preLoaderRoute: typeof DashboardCountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/currency-shop': {
      id: '/dashboard/currency-shop'
      path: '/dashboard/currency-shop'
      fullPath: '/dashboard/currency-shop'
      preLoaderRoute: typeof DashboardCurrencyShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/custom-commands': {
      id: '/dashboard/custom-commands'
      path: '/dashboard/custom-commands'
      fullPath: '/dashboard/custom-commands'
      preLoaderRoute: typeof DashboardCustomCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/economy': {
      id: '/dashboard/economy'
      path: '/dashboard/economy'
      fullPath: '/dashboard/economy'
      preLoaderRoute: typeof DashboardEconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/embed-builder': {
      id: '/dashboard/embed-builder'
      path: '/dashboard/embed-builder'
      fullPath: '/dashboard/embed-builder'
      preLoaderRoute: typeof DashboardEmbedBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/features': {
      id: '/dashboard/features'
      path: '/dashboard/features'
      fullPath: '/dashboard/features'
      preLoaderRoute: typeof DashboardFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/fivem': {
      id: '/dashboard/fivem'
      path: '/dashboard/fivem'
      fullPath: '/dashboard/fivem'
      preLoaderRoute: typeof DashboardFivemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/giveaways': {
      id: '/dashboard/giveaways'
      path: '/dashboard/giveaways'
      fullPath: '/dashboard/giveaways'
      preLoaderRoute: typeof DashboardGiveawaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/global-bans': {
      id: '/dashboard/global-bans'
      path: '/dashboard/global-bans'
      fullPath: '/dashboard/global-bans'
      preLoaderRoute: typeof DashboardGlobalBansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invite-tracker': {
      id: '/dashboard/invite-tracker'
      path: '/dashboard/invite-tracker'
      fullPath: '/dashboard/invite-tracker'
      preLoaderRoute: typeof DashboardInviteTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/jtc': {
      id: '/dashboard/jtc'
      path: '/dashboard/jtc'
      fullPath: '/dashboard/jtc'
      preLoaderRoute: typeof DashboardJtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leaderboard': {
      id: '/dashboard/leaderboard'
      path: '/dashboard/leaderboard'
      fullPath: '/dashboard/leaderboard'
      preLoaderRoute: typeof DashboardLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leveling': {
      id: '/dashboard/leveling'
      path: '/dashboard/leveling'
      fullPath: '/dashboard/leveling'
      preLoaderRoute: typeof DashboardLevelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/live-events': {
      id: '/dashboard/live-events'
      path: '/dashboard/live-events'
      fullPath: '/dashboard/live-events'
      preLoaderRoute: typeof DashboardLiveEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/log-settings': {
      id: '/dashboard/log-settings'
      path: '/dashboard/log-settings'
      fullPath: '/dashboard/log-settings'
      preLoaderRoute: typeof DashboardLogSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/dashboard/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/dashboard/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/moderation': {
      id: '/dashboard/moderation'
      path: '/dashboard/moderation'
      fullPath: '/dashboard/moderation'
      preLoaderRoute: typeof DashboardModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/modmail': {
      id: '/dashboard/modmail'
      path: '/dashboard/modmail'
      fullPath: '/dashboard/modmail'
      preLoaderRoute: typeof DashboardModmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/modules': {
      id: '/dashboard/modules'
      path: '/dashboard/modules'
      fullPath: '/dashboard/modules'
      preLoaderRoute: typeof DashboardModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/music-quiz': {
      id: '/dashboard/music-quiz'
      path: '/dashboard/music-quiz'
      fullPath: '/dashboard/music-quiz'
      preLoaderRoute: typeof DashboardMusicQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/polls': {
      id: '/dashboard/polls'
      path: '/dashboard/polls'
      fullPath: '/dashboard/polls'
      preLoaderRoute: typeof DashboardPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quarantine': {
      id: '/dashboard/quarantine'
      path: '/dashboard/quarantine'
      fullPath: '/dashboard/quarantine'
      preLoaderRoute: typeof DashboardQuarantineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/raid-protection': {
      id: '/dashboard/raid-protection'
      path: '/dashboard/raid-protection'
      fullPath: '/dashboard/raid-protection'
      preLoaderRoute: typeof DashboardRaidProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reaction-roles': {
      id: '/dashboard/reaction-roles'
      path: '/dashboard/reaction-roles'
      fullPath: '/dashboard/reaction-roles'
      preLoaderRoute: typeof DashboardReactionRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reminders': {
      id: '/dashboard/reminders'
      path: '/dashboard/reminders'
      fullPath: '/dashboard/reminders'
      preLoaderRoute: typeof DashboardRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/role-analytics': {
      id: '/dashboard/role-analytics'
      path: '/dashboard/role-analytics'
      fullPath: '/dashboard/role-analytics'
      preLoaderRoute: typeof DashboardRoleAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scheduled-actions': {
      id: '/dashboard/scheduled-actions'
      path: '/dashboard/scheduled-actions'
      fullPath: '/dashboard/scheduled-actions'
      preLoaderRoute: typeof DashboardScheduledActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scheduler': {
      id: '/dashboard/scheduler'
      path: '/dashboard/scheduler'
      fullPath: '/dashboard/scheduler'
      preLoaderRoute: typeof DashboardSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/server-clone': {
      id: '/dashboard/server-clone'
      path: '/dashboard/server-clone'
      fullPath: '/dashboard/server-clone'
      preLoaderRoute: typeof DashboardServerCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/slowmode-scheduler': {
      id: '/dashboard/slowmode-scheduler'
      path: '/dashboard/slowmode-scheduler'
      fullPath: '/dashboard/slowmode-scheduler'
      preLoaderRoute: typeof DashboardSlowmodeSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/starboard': {
      id: '/dashboard/starboard'
      path: '/dashboard/starboard'
      fullPath: '/dashboard/starboard'
      preLoaderRoute: typeof DashboardStarboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/stats-channels': {
      id: '/dashboard/stats-channels'
      path: '/dashboard/stats-channels'
      fullPath: '/dashboard/stats-channels'
      preLoaderRoute: typeof DashboardStatsChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/suggestions': {
      id: '/dashboard/suggestions'
      path: '/dashboard/suggestions'
      fullPath: '/dashboard/suggestions'
      preLoaderRoute: typeof DashboardSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tebex': {
      id: '/dashboard/tebex'
      path: '/dashboard/tebex'
      fullPath: '/dashboard/tebex'
      preLoaderRoute: typeof DashboardTebexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/test-panel': {
      id: '/dashboard/test-panel'
      path: '/dashboard/test-panel'
      fullPath: '/dashboard/test-panel'
      preLoaderRoute: typeof DashboardTestPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/dashboard/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tiktok': {
      id: '/dashboard/tiktok'
      path: '/dashboard/tiktok'
      fullPath: '/dashboard/tiktok'
      preLoaderRoute: typeof DashboardTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/twitch': {
      id: '/dashboard/twitch'
      path: '/dashboard/twitch'
      fullPath: '/dashboard/twitch'
      preLoaderRoute: typeof DashboardTwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verification': {
      id: '/dashboard/verification'
      path: '/dashboard/verification'
      fullPath: '/dashboard/verification'
      preLoaderRoute: typeof DashboardVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/warnings': {
      id: '/dashboard/warnings'
      path: '/dashboard/warnings'
      fullPath: '/dashboard/warnings'
      preLoaderRoute: typeof DashboardWarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/dashboard/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/welcome': {
      id: '/dashboard/welcome'
      path: '/dashboard/welcome'
      fullPath: '/dashboard/welcome'
      preLoaderRoute: typeof DashboardWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/youtube': {
      id: '/dashboard/youtube'
      path: '/dashboard/youtube'
      fullPath: '/dashboard/youtube'
      preLoaderRoute: typeof DashboardYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/_layout': {
      id: '/docs/_layout'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/applications/$submissionId': {
      id: '/dashboard/applications/$submissionId'
      path: '/$submissionId'
      fullPath: '/dashboard/applications/$submissionId'
      preLoaderRoute: typeof DashboardApplicationsSubmissionIdRouteImport
      parentRoute: typeof DashboardApplicationsRoute
    }
    '/dashboard/applications/analytics': {
      id: '/dashboard/applications/analytics'
      path: '/analytics'
      fullPath: '/dashboard/applications/analytics'
      preLoaderRoute: typeof DashboardApplicationsAnalyticsRouteImport
      parentRoute: typeof DashboardApplicationsRoute
    }
    '/dashboard/applications/settings': {
      id: '/dashboard/applications/settings'
      path: '/settings'
      fullPath: '/dashboard/applications/settings'
      preLoaderRoute: typeof DashboardApplicationsSettingsRouteImport
      parentRoute: typeof DashboardApplicationsRoute
    }
    '/dashboard/tickets/$ticketId': {
      id: '/dashboard/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/dashboard/tickets/$ticketId'
      preLoaderRoute: typeof DashboardTicketsTicketIdRouteImport
      parentRoute: typeof DashboardTicketsRoute
    }
    '/dashboard/tickets/settings': {
      id: '/dashboard/tickets/settings'
      path: '/settings'
      fullPath: '/dashboard/tickets/settings'
      preLoaderRoute: typeof DashboardTicketsSettingsRouteImport
      parentRoute: typeof DashboardTicketsRoute
    }
    '/docs/$category/$slug': {
      id: '/docs/$category/$slug'
      path: '/docs/$category/$slug'
      fullPath: '/docs/$category/$slug'
      preLoaderRoute: typeof DocsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/applications/forms/$formId': {
      id: '/dashboard/applications/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/dashboard/applications/forms/$formId'
      preLoaderRoute: typeof DashboardApplicationsFormsFormIdRouteImport
      parentRoute: typeof DashboardApplicationsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminGlobalBansRoute: typeof AdminGlobalBansRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGlobalBansRoute: AdminGlobalBansRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardApplicationsRouteChildren {
  DashboardApplicationsSubmissionIdRoute: typeof DashboardApplicationsSubmissionIdRoute
  DashboardApplicationsAnalyticsRoute: typeof DashboardApplicationsAnalyticsRoute
  DashboardApplicationsSettingsRoute: typeof DashboardApplicationsSettingsRoute
  DashboardApplicationsFormsFormIdRoute: typeof DashboardApplicationsFormsFormIdRoute
}

const DashboardApplicationsRouteChildren: DashboardApplicationsRouteChildren = {
  DashboardApplicationsSubmissionIdRoute:
    DashboardApplicationsSubmissionIdRoute,
  DashboardApplicationsAnalyticsRoute: DashboardApplicationsAnalyticsRoute,
  DashboardApplicationsSettingsRoute: DashboardApplicationsSettingsRoute,
  DashboardApplicationsFormsFormIdRoute: DashboardApplicationsFormsFormIdRoute,
}

const DashboardApplicationsRouteWithChildren =
  DashboardApplicationsRoute._addFileChildren(
    DashboardApplicationsRouteChildren,
  )

interface DashboardTicketsRouteChildren {
  DashboardTicketsTicketIdRoute: typeof DashboardTicketsTicketIdRoute
  DashboardTicketsSettingsRoute: typeof DashboardTicketsSettingsRoute
}

const DashboardTicketsRouteChildren: DashboardTicketsRouteChildren = {
  DashboardTicketsTicketIdRoute: DashboardTicketsTicketIdRoute,
  DashboardTicketsSettingsRoute: DashboardTicketsSettingsRoute,
}

const DashboardTicketsRouteWithChildren =
  DashboardTicketsRoute._addFileChildren(DashboardTicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  GuildsRoute: GuildsRoute,
  DashboardLayoutRoute: DashboardLayoutRoute,
  DashboardActivityHeatmapRoute: DashboardActivityHeatmapRoute,
  DashboardAiAutomodRoute: DashboardAiAutomodRoute,
  DashboardAiChatRoute: DashboardAiChatRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApplicationsRoute: DashboardApplicationsRouteWithChildren,
  DashboardAutoReportsRoute: DashboardAutoReportsRoute,
  DashboardAutoRespondersRoute: DashboardAutoRespondersRoute,
  DashboardAutomodRoute: DashboardAutomodRoute,
  DashboardBackupsRoute: DashboardBackupsRoute,
  DashboardBirthdaysRoute: DashboardBirthdaysRoute,
  DashboardBotHealthRoute: DashboardBotHealthRoute,
  DashboardBotSettingsRoute: DashboardBotSettingsRoute,
  DashboardChangelogRoute: DashboardChangelogRoute,
  DashboardCharactersRoute: DashboardCharactersRoute,
  DashboardCommandsRoute: DashboardCommandsRoute,
  DashboardConfessionsRoute: DashboardConfessionsRoute,
  DashboardCountingRoute: DashboardCountingRoute,
  DashboardCurrencyShopRoute: DashboardCurrencyShopRoute,
  DashboardCustomCommandsRoute: DashboardCustomCommandsRoute,
  DashboardEconomyRoute: DashboardEconomyRoute,
  DashboardEmbedBuilderRoute: DashboardEmbedBuilderRoute,
  DashboardFeaturesRoute: DashboardFeaturesRoute,
  DashboardFivemRoute: DashboardFivemRoute,
  DashboardGiveawaysRoute: DashboardGiveawaysRoute,
  DashboardGlobalBansRoute: DashboardGlobalBansRoute,
  DashboardInviteTrackerRoute: DashboardInviteTrackerRoute,
  DashboardJtcRoute: DashboardJtcRoute,
  DashboardLeaderboardRoute: DashboardLeaderboardRoute,
  DashboardLevelingRoute: DashboardLevelingRoute,
  DashboardLiveEventsRoute: DashboardLiveEventsRoute,
  DashboardLogSettingsRoute: DashboardLogSettingsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardModerationRoute: DashboardModerationRoute,
  DashboardModmailRoute: DashboardModmailRoute,
  DashboardModulesRoute: DashboardModulesRoute,
  DashboardMusicQuizRoute: DashboardMusicQuizRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPollsRoute: DashboardPollsRoute,
  DashboardQuarantineRoute: DashboardQuarantineRoute,
  DashboardRaidProtectionRoute: DashboardRaidProtectionRoute,
  DashboardReactionRolesRoute: DashboardReactionRolesRoute,
  DashboardRemindersRoute: DashboardRemindersRoute,
  DashboardRoleAnalyticsRoute: DashboardRoleAnalyticsRoute,
  DashboardScheduledActionsRoute: DashboardScheduledActionsRoute,
  DashboardSchedulerRoute: DashboardSchedulerRoute,
  DashboardServerCloneRoute: DashboardServerCloneRoute,
  DashboardSlowmodeSchedulerRoute: DashboardSlowmodeSchedulerRoute,
  DashboardStarboardRoute: DashboardStarboardRoute,
  DashboardStatsChannelsRoute: DashboardStatsChannelsRoute,
  DashboardSuggestionsRoute: DashboardSuggestionsRoute,
  DashboardTebexRoute: DashboardTebexRoute,
  DashboardTestPanelRoute: DashboardTestPanelRoute,
  DashboardTicketsRoute: DashboardTicketsRouteWithChildren,
  DashboardTiktokRoute: DashboardTiktokRoute,
  DashboardTwitchRoute: DashboardTwitchRoute,
  DashboardVerificationRoute: DashboardVerificationRoute,
  DashboardWarningsRoute: DashboardWarningsRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardWelcomeRoute: DashboardWelcomeRoute,
  DashboardYoutubeRoute: DashboardYoutubeRoute,
  DocsLayoutRoute: DocsLayoutRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsCategorySlugRoute: DocsCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
